# Generated by Django 4.1.1 on 2022-10-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('platform', models.CharField(max_length=50)),
                ('completion', models.CharField(default='0%', max_length=50)),
            ],
        ),
    ]
